# Generated by Django 3.1.5 on 2021-08-01 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deneme_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deneme_app.myuser'),
            preserve_default=False,
        ),
    ]
